apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-tests-go-aqcaphaa
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/e2e-tests-go-aqcaphaa:301572ae36e1e6f3af0dafdf8d84492bf5fd79e4
        name: container-image  
